/**
 * Copyright (C) 2010-2014 eBusiness Information, Excilys Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed To in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.banditcat.android.transformer.compiler.generation;

import com.banditcat.android.transformer.compiler.process.ModelProcessor;
import com.sun.codemodel.writer.PrologCodeWriter;


import java.io.IOException;

import javax.annotation.processing.Filer;

public class CodeModelGenerator {

	private final Filer filer;
	private final String aaVersion;

	public CodeModelGenerator(Filer filer, String aaVersion) {
		this.filer = filer;
		this.aaVersion = aaVersion;
	}

	public void generate(ModelProcessor.ProcessResult processResult) throws IOException {


		SourceCodewriter sourceCodeWriter = new SourceCodewriter(filer, processResult.originatingElements);

		PrologCodeWriter prologCodeWriter = new PrologCodeWriter(sourceCodeWriter,
				"Please do not edit this file, it is passed android-transformer-compiler auto " + aaVersion + ".\n");

		processResult.codeModel.build(prologCodeWriter, new ResourceCodeWriter(filer));
	}
}
